from . import (
    c11,
    hallway_ground,
    hallway_upper,
    j23,
    med_bay,
    engineering_bay,
    reactor_catwalk,
    maintenance_tunnels,
    data_core,
    overseer_office,
    security_office,
    under_construction,
    vault_door_room,
)

SCENES = {
    "c11": c11.c11,
    "data_core": data_core.data_core,
    "engineering_bay": engineering_bay.engineering_bay,
    "hallway_ground": hallway_ground.hallway_ground,
    "hallway_upper": hallway_upper.hallway_upper,
    "j23": j23.j23,
    "maintenance_tunnels": maintenance_tunnels.maintenance_tunnels,
    "med_bay": med_bay.med_bay,
    "overseer_office": overseer_office.overseer_office,
    "reactor_catwalk": reactor_catwalk.reactor_catwalk,
    "security_office": security_office.security_office,
    "under_construction": under_construction.under_construction,
    "vault_door_room": vault_door_room.vault_door_room,
}
